class Language {
  int id;
  String name;
  String code;
  Language(this.id, this.name, this.code);

  static List<Language> getlanguages() {
    return <Language>[
      Language(1, 'English', 'en'),
      Language(2, 'Hindi', 'hi'),
      Language(4, 'French', 'fr'),
      Language(5, 'Afrikaans', 'af'),
      Language(6, 'Albanian', 'sq'),
      Language(7, 'Amharic', 'am'),
      Language(8, 'Arabic', 'ar'),
      Language(9, 'Armenian', 'hy'),
      Language(10, 'Azerbaijani', 'az'),
      Language(11, 'Basque', 'eu'),
      Language(12, 'Belarusian', 'be'),
      Language(13, 'Bengali', 'bn'),
      Language(14, 'Bosnian', 'bs'),
      Language(15, 'Bulgarian', 'bg'),
      Language(16, 'Catalan', 'ca'),
      Language(17, 'Cebuano', 'ceb'),
      Language(18, 'Chinese (Simplified)', 'zh-CN'),
      Language(19, 'Chinese (Traditional)	', 'zh-TW'),
      Language(20, 'Corsican', 'co'),
      Language(21, 'Croatian', 'hr'),
      Language(22, 'Czech', 'cs'),
      Language(23, 'Danish', 'da'),
      Language(25, 'Dutch', 'nl'),
      Language(26, 'Esperanto', 'eo'),
      Language(27, 'Estonian', 'et'),
      Language(28, 'Finnish', 'fi'),
      Language(29, 'Frisian', 'fy'),
      Language(30, 'Galician', 'gl'),
      Language(31, 'Georgian', 'ka'),
      Language(32, 'German', 'de'),
      Language(33, 'Greek', 'el'),
      Language(34, 'Gujarati', 'gu'),
      Language(35, 'Haitian Creole	', 'ht'),
      Language(36, 'Hausa', 'ha'),
      Language(37, 'Hawaiian', 'haw'),
      Language(38, 'Hebrew', 'hi'),
      Language(39, 'Hmong', 'hmn'),
      Language(40, 'Hungarian', 'hu'),
      Language(41, 'Icelandic', 'is'),
      Language(42, 'Igbo', 'ig'),
      Language(43, 'Indonesian', 'id'),
      Language(44, 'Irish', 'ga'),
      Language(45, 'Italian', 'it'),
      Language(46, 'Japanese', 'ja'),
      Language(46, 'Javanese', 'jv'),
      Language(47, 'Kannada', 'kn'),
      Language(48, 'Kazakh', 'kk'),
      Language(49, 'Khmer', 'km'),
      Language(50, 'Kinyarwanda', 'rw'),
      Language(51, 'Korean', 'ko'),
      Language(52, 'Kurdish', 'ku'),
      Language(53, 'Kyrgyz', 'ky'),
      Language(54, 'Lao', 'lo'),
      Language(55, 'Latin', 'la'),
      Language(56, 'Latvian', 'lv'),
      Language(57, 'Lithuanian', 'lt'),
      Language(58, 'Luxembourgish', 'lb'),
      Language(59, 'Macedonian', 'mk'),
      Language(60, 'Malagasy', 'mg'),
      Language(61, 'Malay', 'ms'),
      Language(62, 'Malayalam', 'ml'),
      Language(63, 'Maltese', 'mt'),
      Language(64, 'Maori', 'mi'),
      Language(65, 'Marathi', 'mr'),
      Language(66, 'Mongolian', 'mn'),
      Language(67, 'Myanmar (Burmese)	', 'ne'),
      Language(68, 'Nepali', 'ne'),
      Language(69, 'Norwegian', 'no'),
      Language(70, 'Nyanja (Chichewa)	', 'ny'),
      Language(71, 'Odia (Oriya)', 'or'),
      Language(72, 'Pashto', 'ps'),
      Language(73, 'Persian', 'fa'),
      Language(74, 'Polish', 'pl'),
      Language(75, 'Portuguese (Portugal, Brazil)', 'pt'),
      Language(76, 'Punjabi', 'pa'),
      Language(77, 'Romanian', 'ro'),
      Language(78, 'Russian', 'ru'),
      Language(79, 'Samoan', 'sm'),
      Language(80, 'Scots Gaelic', 'gd'),
      Language(81, 'Serbian', 'sr'),
      Language(82, 'Sesotho', 'st'),
      Language(83, 'Shona', 'sn'),
      Language(84, 'Sindhi', 'sd'),
      Language(85, 'Sinhala (Sinhalese)', 'si'),
      Language(86, 'Slovak', 'sk'),
      Language(87, 'Slovenian', 'sl'),
      Language(89, 'Somali', 'so'),
      Language(90, 'Spanish', 'es'),
      Language(91, 'Sundanese', 'su'),
      Language(92, 'Swahili', 'sw'),
      Language(93, 'Swedish', 'sv'),
      Language(94, 'Tagalog (Filipino)', 'tl'),
      Language(85, 'Tajik', 'tg'),
      Language(96, 'Tamil', 'ta'),
      Language(97, 'Tatar', 'tt'),
      Language(98, 'Telugu', 'te'),
      Language(99, 'Thai', 'th'),
      Language(101, 'Turkish', 'tr'),
      Language(102, 'Turkmen', 'tk'),
      Language(103, 'Ukrainian', 'uk'),
      Language(104, 'Urdu', 'ur'),
      Language(105, 'Uyghur', 'ug'),
      Language(106, 'Uzbek', 'uz'),
      Language(107, 'Vietnamese', 'vi'),
      Language(109, 'Welsh', 'xh'),
      Language(110, 'Xhosa', 'xh'),
      Language(111, 'Yiddish', 'yi'),
      Language(112, 'Yoruba', 'yo'),
      Language(113, 'Zulu', 'zu'),
    ];
  }
}
